import {emptyLedger,validateLedger,makeBackup,validateBackup,formatMoney,monthlySummary,ownIncomeCategory} from './ledger-model.js?v=monthly-summary-1';
const live=document.body.dataset.appMode==='live';
let liveStore=null, liveRevision=0, liveReady=false, liveLoaded=false, writeBusy=false, pendingState=null, formRevision=0, draftId=null;
const screen = document.getElementById('screen');
const parts = new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
const part = name => parts.find(p=>p.type===name).value;
const today = `${part('year')}-${part('month')}-${part('day')}`, currentMonth=today.slice(0,7);
const prevDate = new Date(`${currentMonth}-15T12:00:00Z`); prevDate.setUTCMonth(prevDate.getUTCMonth()-1);
const previousMonth = prevDate.toISOString().slice(0,7);
const exampleDay = Number(part('day'))>1 ? `${currentMonth}-${String(Number(part('day'))-1).padStart(2,'0')}` : today;
const money = formatMoney;
const dateName = value => new Intl.DateTimeFormat('es-AR',{day:'numeric',month:'long',year:'numeric',timeZone:'America/Argentina/Buenos_Aires'}).format(new Date(value+'T12:00:00Z'));
function monthDate(value,end=false){if(value===currentMonth)return today;return value+'-'+(end?String(new Date(Date.UTC(Number(value.slice(0,4)),Number(value.slice(5,7)),0)).getUTCDate()).padStart(2,'0'):'01');}
const monthName = value => new Intl.DateTimeFormat('es-AR',{month:'long',year:'numeric',timeZone:'America/Argentina/Buenos_Aires'}).format(new Date(value+'-15T12:00:00Z'));
const escape = text => String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let tab='home', month=currentMonth, location='cash', salary=false, historical=false;
const operations = [
 {kind:'income',incomeSource:'own',description:'Sueldo diario',legs:[{location:'cash',date:exampleDay,cents:1500000}]},
 {kind:'transfer',description:'De Efectivo a Virtual',legs:[{location:'cash',date:exampleDay,cents:-700000},{location:'virtual',date:exampleDay,cents:700000}]},
 {kind:'expense',incomeSource:'own',description:'Viaje al trabajo',legs:[{location:'cash',date:today,cents:-85000}]},
 {kind:'expense',incomeSource:'own',description:'Compra del día',legs:[{location:'virtual',date:today,cents:-100000}]},
 {kind:'saving-out',description:'Enviado a Ahorro / Préstamos',legs:[{location:'virtual',date:today,cents:-150000}]},
 {kind:'income',incomeSource:'contribution',description:'Aporte para pagar tarjeta',legs:[{location:'virtual',date:exampleDay,cents:30000000}]},
 {kind:'expense',description:'Pago completo del resumen',legs:[{location:'virtual',date:today,cents:-100000000}]},
 {kind:'income',incomeSource:'own',description:'Ingreso propio de ejemplo',legs:[{location:'virtual',date:exampleDay,cents:100000000}]},
 {kind:'income',incomeSource:'own',description:'Ingresos del mes anterior',legs:[{location:'cash',date:previousMonth+'-10',cents:1200000}]},
 {kind:'expense',incomeSource:'own',description:'Gastos del mes anterior',legs:[{location:'cash',date:previousMonth+'-12',cents:-800000}]}
];
const categories = [{id:'food',name:'Comida'},{id:'outings',name:'Salidas'},{id:'fuel',name:'Combustible'},{id:'transport',name:'Transporte'},{id:'card',name:'Tarjeta'},{id:'uncategorized',name:'Sin categoría'}];
operations.forEach((op,i)=>{op.id=crypto.randomUUID();if(op.kind==='expense')op.categoryId=({2:'transport',3:'food',6:'card'})[i]||'uncategorized';});
let editingId=null;
if(live){operations.splice(0);categories.splice(0,categories.length,...emptyLedger().categories);}
const categoryName=id=>categories.find(c=>c.id===id)?.name||'Sin categoría';
const rows = () => operations.flatMap(op=>op.legs.map(leg=>({...leg,op})));
const balance = (loc,m=month) => rows().filter(r=>r.date.slice(0,7)===m&&(!loc||r.location===loc)).reduce((sum,r)=>sum+r.cents,0);
function monthBar(title){return `<h2 class="page-title">${title}</h2><div class="month-navigation"><button class="month-arrow" type="button" data-month-step="-1" aria-label="Mes anterior">‹</button><button class="month-title" type="button" id="choose-month" aria-label="Elegir mes"><strong>${monthName(month)}</strong><small>${month===currentMonth?'Mes actual':'Mes consultado'}</small></button><button class="month-arrow" type="button" data-month-step="1" aria-label="Mes siguiente">›</button></div><div id="month-chooser" class="month-chooser" hidden><label>Ir directamente a un mes<input id="month-picker" type="month" value="${month}" aria-label="Mes consultado"></label></div>`;}
function shiftMonth(step){const date=new Date(month+'-15T12:00:00Z');date.setUTCMonth(date.getUTCMonth()+step);month=date.toISOString().slice(0,7);historical=month!==currentMonth;render();}

function toast(text){const el=document.getElementById('toast');el.textContent=text;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.textContent='',4500);}
function go(next){tab=next;if(['cash','virtual','evolution'].includes(next)){month=currentMonth;historical=false;}render();if(next==='cash'||next==='virtual')requestAnimationFrame(()=>document.getElementById('today')?.scrollIntoView({block:'center',behavior:'smooth'}));else if(next==='evolution')requestAnimationFrame(()=>document.getElementById('current-evolution')?.scrollIntoView({block:'center',behavior:'smooth'}));else window.scrollTo({top:0});}
function monthDays(value){const year=Number(value.slice(0,4)),number=Number(value.slice(5,7));const count=new Date(Date.UTC(year,number,0)).getUTCDate();return Array.from({length:count},(_,i)=>`${value}-${String(i+1).padStart(2,'0')}`);}
function consecutiveMonths(){const years=[Number(currentMonth.slice(0,4)),...rows().map(r=>Number(r.date.slice(0,4)))];const first=Math.min(...years),last=Math.max(...years);return Array.from({length:(last-first+1)*12},(_,i)=>`${first+Math.floor(i/12)}-${String(i%12+1).padStart(2,'0')}`);}

function monthTotals(m){let income=0,contributions=0,expense=0,savings=0;for(const r of rows().filter(r=>r.date.slice(0,7)===m)){
 if(r.op.kind==='income'){if(r.op.incomeSource==='contribution')contributions+=r.cents;else income+=r.cents;}
 if(r.op.kind==='expense')expense-=r.cents;
 if(r.op.kind==='saving-out'||r.op.kind==='saving-in')savings-=r.cents;
 }return {income,contributions,expense,savings,netExpense:expense-contributions};}
const tableMoney = cents => new Intl.NumberFormat('es-AR',{minimumFractionDigits:cents%100?2:0,maximumFractionDigits:2}).format(cents/100);
function entry(r){const label=r.op.kind==='transfer'?'Transferencia · no es ingreso ni gasto':r.op.kind==='month'?'Pase vinculado · sin arrastre automático':r.op.kind.startsWith('saving')?'Ahorro / Préstamos':r.op.kind==='income'?(r.op.incomeSource==='contribution'?'Aporte de otra persona':'Ingreso propio'):'Pago completo';return `<button type="button" class="entry entry-button" data-edit="${r.op.id}"><div><strong>${escape(r.description || r.op.description)}</strong><small>${label}${r.op.kind==='expense'?' · '+escape(categoryName(r.op.categoryId)):''} · Editar</small></div><span class="money ${r.cents>=0?'positive':'negative'}">${r.cents>=0?'+':'−'}${money(Math.abs(r.cents))}</span></button>`;}
function summaryOfMonth(){
 const t=monthlySummary({operations,categories},month);
 const line=(label,cents)=>`<div class="summary-line"><span>${label}</span><b>${money(cents)}</b></div>`;
 return `<section class="monthly-summary" aria-label="Resumen del mes"><h2>Resumen del mes</h2><p class="summary-caption">${monthName(month)} · Efectivo + Virtual</p><section class="summary-card"><h3>Mis ingresos</h3>${line('Sueldo mío · diario',t.salary)}${line('Sueldo Mel',t.mel)}${line('Sueldo Misa',t.misa)}${line('Extras',t.extra)}<div class="summary-total"><small>TOTAL DE MIS INGRESOS</small><strong id="monthly-own-income">${money(t.income)}</strong></div></section><section class="summary-card"><h3>Ingresos ajenos para pagos</h3>${line('Aportes recibidos este mes',t.contributions)}<p class="summary-note">Separados de tus ingresos propios.</p></section><section class="summary-card"><h3>Mis gastos</h3>${line('Total de gastos en Categorías',t.expense)}${line('− Ingresos ajenos para pagos',t.contributions)}<div class="summary-total summary-net"><small>TOTAL REAL DE MIS GASTOS</small><strong id="monthly-own-expense">${money(t.netExpense)}</strong></div><p class="summary-note">Pagos completos del mes menos los aportes ajenos para esos pagos.</p></section><section class="summary-card summary-savings"><h3>Ahorro / Préstamos</h3><div class="summary-total"><small>TOTAL ENVIADO MENOS LO QUE VOLVIÓ</small><strong id="monthly-savings">${money(t.savings)}</strong></div><p class="summary-note">Este movimiento se muestra aparte de tus gastos e ingresos propios.</p></section></section>`;
}
function home(){const otherMonths=[...new Set(rows().map(r=>r.date.slice(0,7)))].filter(m=>m!==month);const others=otherMonths.reduce((s,m)=>s+balance(null,m),0);return `${monthBar('Inicio')}<section class="hero"><p>Total disponible · ${monthName(month)}</p><div class="balance">${money(balance())}</div><small>Efectivo + Virtual del mes consultado</small></section><div class="accounts"><button class="account-card" data-go="cash"><span>Efectivo</span><strong>${money(balance('cash'))}</strong><small>Dinero actual →</small></button><button class="account-card" data-go="virtual"><span>Virtual</span><strong>${money(balance('virtual'))}</strong><small>Dinero actual →</small></button></div><div class="actions"><button class="primary" data-move="salary">+ Sueldo diario</button><button class="action" data-move="cash">Movimiento Efectivo</button><button class="action" data-move="virtual">Movimiento Virtual</button></div><p class="muted">En otros meses: ${money(others)}. Cada saldo permanece en su mes hasta que registres un pase.</p>${summaryOfMonth()}`;}
function account(loc){const title=loc==='cash'?'Efectivo':'Virtual';const relevant=rows().filter(r=>r.location===loc&&r.date.slice(0,7)===month);const days=monthDays(month);return `${monthBar(title)}<section class="hero"><p>Dinero actual · ${monthName(month)}</p><div class="balance">${money(balance(loc))}</div></section><div class="section-head"><h3>Movimientos del mes</h3></div><div class="days">${days.length?days.map(day=>{const records=relevant.filter(r=>r.date===day);return `<section class="day ${day===today?'today':''}" ${day===today?'id="today"':''}><div class="date-col"><b>${Number(day.slice(8))}</b>${day===today?'HOY':new Intl.DateTimeFormat('es-AR',{weekday:'short',timeZone:'America/Argentina/Buenos_Aires'}).format(new Date(day+'T12:00:00Z'))}</div><div>${records.length?records.map(entry).join(''):`<div class="empty">${day===today?'Sin movimientos hoy':'Sin movimientos'}</div>`}</div></section>`;}).join(''):'<p class="empty">No hay movimientos en este mes de ejemplo.</p>'}</div><div class="section-head"><button class="action" data-move="${loc}">+ Movimiento ${title}</button></div>`;}
function evolution(){const months=consecutiveMonths();return `<div class="section-head"><h2>Evolución</h2><span class="pill">Mes a mes</span></div><p class="muted">Importes en pesos · Efectivo + Virtual. Pagos completos, sin dividirlos por persona.</p><div class="evolution">${months.map(m=>{const t=monthTotals(m);return `<details data-evolution-month="${m}" ${m===month?'id="current-evolution" class="selected-month"':''}><summary class="evolution-row"><div class="evolution-month"><b>${monthName(m)}</b><span class="pill">${m===currentMonth?'Mes actual':'Ver detalle'} <span aria-hidden="true">⌄</span></span></div><div class="evolution-metrics"><div><small>Ingresos propios</small><strong class="positive">${money(t.income)}</strong></div><div><small>Aportes recibidos</small><strong class="contribution">${money(t.contributions)}</strong></div><div><small>Gastos completos</small><strong>${money(t.expense)}</strong></div><div><small>Ahorro / Préstamos</small><strong>${money(t.savings)}</strong></div></div></summary><div class="detail-body"><p class="muted">${monthName(m)}</p><div class="calculation"><div class="detail-line"><span>Gastos pagados</span><b>${money(t.expense)}</b></div><div class="detail-line"><span>− Aportes recibidos</span><b>${money(t.contributions)}</b></div><div class="detail-line"><span><b>Gastos menos aportes</b></span><b>${money(t.netExpense)}</b></div><p class="muted">Resta de este mes. Los aportes no son sueldo ni ingreso propio. Si entran en otro mes, figuran allí.</p></div>${rows().filter(r=>r.date.slice(0,7)===m&&(['income','expense'].includes(r.op.kind)||r.op.kind.startsWith('saving'))).map(r=>`<div class="detail-line"><span>${escape(r.description || r.op.description)}<small>${r.op.kind==='income'?(r.op.incomeSource==='contribution'?'Aporte de otra persona':'Ingreso propio'):r.op.kind==='expense'?'Pago completo':'Ahorro / Préstamos'}</small></span><span>${money(Math.abs(r.cents))}</span></div>`).join('')}</div></details>`;}).join('')}</div>`;}
function movements(){const items=operations.map(op=>{const visible=op.legs.filter(leg=>leg.date.slice(0,7)===month);if(!visible.length)return null;const first=visible[0],linked=op.kind==='transfer'||op.kind==='month';const places=[...new Set(op.legs.map(leg=>leg.location==='cash'?'Efectivo':'Virtual'))].join(' → ');const title=op.kind==='month'?`${dateName(op.legs[0].date)} → ${dateName(op.legs[1].date)}`:op.description;return {date:first.date,html:`<button type="button" class="entry entry-button" data-edit="${op.id}"><div><strong>${escape(title)}</strong><small>${places} · ${linked?'Una operación vinculada':op.kind.startsWith('saving')?'Ahorro / Préstamos':op.kind==='income'?(op.incomeSource==='contribution'?'Aporte de otra persona':'Ingreso propio'):'Pago completo · '+escape(categoryName(op.categoryId))} · Editar</small></div><span class="money ${linked?'':first.cents>=0?'positive':'negative'}">${linked?'':first.cents>=0?'+':'−'}${money(Math.abs(first.cents))}</span></button>`};}).filter(Boolean).sort((a,b)=>b.date.localeCompare(a.date));const days=[...new Set(items.map(item=>item.date))];return `${monthBar('Movimientos')}<p class="muted">Todo Efectivo y Virtual del mes, incluidos aportes de otras personas, transferencias, pases y Ahorro / Préstamos.</p><div class="days">${days.length?days.map(day=>`<section class="day"><div class="date-col"><b>${Number(day.slice(8))}</b>${new Intl.DateTimeFormat('es-AR',{weekday:'short',timeZone:'America/Argentina/Buenos_Aires'}).format(new Date(day+'T12:00:00Z'))}</div><div>${items.filter(item=>item.date===day).map(item=>item.html).join('')}</div></section>`).join(''):'<div class="empty">No hay movimientos en este mes de ejemplo.</div>'}</div>`;}
function categoryPage(){const expenses=rows().filter(r=>r.op.kind==='expense'&&r.date.slice(0,7)===month);return `${monthBar('Categorías')}<section class="hero"><p>Gastos del mes · Efectivo + Virtual</p><div class="balance">${money(monthTotals(month).expense)}</div><small>Transferencias y Ahorro / Préstamos no se cuentan como gastos.</small></section><form id="category-form" class="category-create"><label>Nueva categoría<input id="category-name" maxlength="40" required placeholder="Por ejemplo, Salud"></label><button type="submit" class="primary">Agregar categoría</button><p id="category-error" role="alert"></p></form><div class="category-list">${categories.map(c=>{const records=expenses.filter(r=>r.op.categoryId===c.id).sort((a,b)=>b.date.localeCompare(a.date));const total=records.reduce((sum,r)=>sum-r.cents,0);return `<details class="category-card" data-category-id="${c.id}"><summary><div><h3>${escape(c.name)}</h3><strong>${money(total)}</strong></div><small>${records.length} ${records.length===1?'gasto':'gastos'} · Ver detalle <span class="category-chevron" aria-hidden="true">⌄</span></small></summary><div class="category-expenses">${records.length?records.map(r=>`<div class="category-record"><div class="category-date">${new Intl.DateTimeFormat('es-AR',{day:'numeric',month:'short',timeZone:'America/Argentina/Buenos_Aires'}).format(new Date(r.date+'T12:00:00Z'))} · ${r.location==='cash'?'Efectivo':'Virtual'}</div>${entry(r)}</div>`).join(''):'<p class="empty">Sin gastos en esta categoría durante el mes seleccionado.</p>'}</div>${c.id!=='uncategorized'?`<div class="category-actions"><button type="button" data-rename-category="${c.id}">Renombrar</button><button type="button" data-remove-category="${c.id}">Quitar</button></div>`:'<small>Conserva los gastos de categorías que quitaste.</small>'}</details>`;}).join('')}</div><p class="muted">Tocá una categoría para consultar sus gastos del mes. Tocá un gasto para editarlo o eliminarlo.</p>`;}
function backup(){if(live)return `<h2>Respaldo</h2><p class="muted">El guardado en Firebase y la copia en Drive se confirman por separado.</p><section class="info-card" data-drive-backup></section><button class="action" type="button" id="export-ledger">Descargar copia completa en JSON</button><section class="info-card"><h3>Copias de Gastos</h3><button type="button" class="action" data-drive-action="list">Consultar copias</button><ul data-drive-files></ul><p class="muted">Las copias de la prueba ficticia se conservan, pero no se importan como movimientos. Restaurar requiere confirmación y una copia previa en Drive.</p><label>Restaurar desde archivo JSON<input id="import-ledger" type="file" accept=".json,application/json"></label></section><p id="restore-live-status" role="status"></p>`;return `<h2>Respaldo</h2><p>Esta demostración no guarda datos financieros. Los cambios se descartan al recargar.</p><a class="action" href="drive-respaldos.html">Abrir prueba de respaldo en Google Drive</a>`;}
function render(){if(live&&!liveLoaded){screen.innerHTML='<section class="info-card"><h2>Tu cuenta privada</h2><p>Conectá tu cuenta y confirmá el acceso para ver o registrar movimientos.</p></section>';return;}screen.innerHTML=(historical?`<div class="history-banner"><span>Consultando ${monthName(month)}</span><button id="return-current" type="button">Volver al mes actual</button></div>`:'')+(tab==='categories'?categoryPage():tab==='movements'?movements():tab==='home'?home():tab==='cash'?account('cash'):tab==='virtual'?account('virtual'):tab==='evolution'?evolution():backup());document.querySelectorAll('nav button').forEach(b=>{if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});const activeTab=document.querySelector('nav button[aria-current=page]'),navBar=document.querySelector('nav');if(activeTab){const left=activeTab.offsetLeft,right=left+activeTab.offsetWidth;if(left<navBar.scrollLeft)navBar.scrollTo({left:left-8,behavior:'smooth'});else if(right>navBar.scrollLeft+navBar.clientWidth)navBar.scrollTo({left:right-navBar.clientWidth+8,behavior:'smooth'});}document.getElementById('open-backup').setAttribute('aria-pressed',String(tab==='backup'));if(live){screen.innerHTML=screen.innerHTML.replaceAll('en este mes de ejemplo','en este mes');syncWriteButtons();}document.getElementById('month-picker')?.addEventListener('change',e=>{if(e.target.value){month=e.target.value;historical=month!==currentMonth;render();}});}
document.addEventListener('click',async event=>{const edit=event.target.closest('[data-edit]');if(edit){openEdit(edit.dataset.edit);return;}const rename=event.target.closest('[data-rename-category]');if(rename){if(writeBusy)return;const c=categories.find(c=>c.id===rename.dataset.renameCategory);const revision=liveRevision;const name=prompt('Nuevo nombre de la categoría',c.name)?.trim();if(name){if(name.length>40||categories.some(other=>other.id!==c.id&&other.name.toLocaleLowerCase()===name.toLocaleLowerCase())){toast('Elegí un nombre único de hasta 40 caracteres.');return;}await change(data=>{data.categories.find(item=>item.id===c.id).name=name;},'Categoría actualizada.',revision);}return;}const remove=event.target.closest('[data-remove-category]');if(remove){if(writeBusy)return;const c=categories.find(c=>c.id===remove.dataset.removeCategory);const revision=liveRevision;if(confirm('¿Quitar '+c.name+'? Sus gastos se conservarán como Sin categoría.'))await change(data=>{data.operations.forEach(op=>{if(op.categoryId===c.id)op.categoryId='uncategorized';});data.categories.splice(data.categories.findIndex(item=>item.id===c.id),1);},'Categoría eliminada; gastos conservados.',revision);return;}const step=event.target.closest('[data-month-step]');if(step){shiftMonth(Number(step.dataset.monthStep));return;}if(event.target.closest('#choose-month')){const chooser=document.getElementById('month-chooser');chooser.hidden=!chooser.hidden;if(!chooser.hidden)document.getElementById('month-picker').focus();return;}if(event.target.closest('#return-current')){month=currentMonth;historical=false;go(tab);return;}const goButton=event.target.closest('[data-go]');if(goButton)go(goButton.dataset.go);const nav=event.target.closest('[data-tab]');if(nav)go(nav.dataset.tab);const move=event.target.closest('[data-move]');if(move)openMovement(move.dataset.move);const notice=event.target.closest('[data-toast]');if(notice)toast(notice.dataset.toast);if(event.target.closest('#export-ledger'))await exportLedger();});
const dialog=document.getElementById('movement'),form=document.getElementById('movement-form'),type=document.getElementById('type');
function categoryOptions(selected=''){document.getElementById('category').innerHTML='<option value="">Elegir categoría</option>'+categories.map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${escape(c.name)}</option>`).join('');}
function openMovement(which){if(writeBusy||(live&&!liveReady)){toast('Esperá a que se confirme el acceso y el guardado.');return;}form.reset();draftId=crypto.randomUUID();formRevision=liveRevision;editingId=null;salary=which==='salary';location=salary?'cash':which;document.getElementById('dialog-title').textContent=salary?'+ Sueldo diario':`Movimiento ${location==='cash'?'Efectivo':'Virtual'}`;document.getElementById('date').value=today;document.getElementById('source-month').value=monthDate(month,true);const next=new Date(currentMonth+'-15T12:00:00Z');next.setUTCMonth(next.getUTCMonth()+1);document.getElementById('destination').value=monthDate(month===currentMonth?next.toISOString().slice(0,7):currentMonth);type.value=salary?'income':'expense';document.getElementById('edit-location').value=location;document.getElementById('form-error').textContent='';categoryOptions();fields();dialog.showModal();document.getElementById('amount').focus();}
function openEdit(id){const op=operations.find(op=>op.id===id);if(!op||writeBusy||(live&&!liveReady))return;openMovement(op.legs[0].location);editingId=id;salary=false;type.value=op.kind;document.getElementById('dialog-title').textContent='Editar movimiento';document.getElementById('amount').value=(Math.abs(op.legs[0].cents)/100).toFixed(2).replace('.',',');document.getElementById('description').value=op.description;document.getElementById('date').value=op.legs[0].date;document.getElementById('source-month').value=op.legs[0].date;document.getElementById('destination').value=op.legs[1]?.date||today;form.elements.incomeSource.value=op.incomeSource==='contribution'?'contribution':ownIncomeCategory(op);categoryOptions(op.categoryId);fields();}
function fields(){const isIncome=type.value==='income';for(const id of ['type-label','description-label'])document.getElementById(id).hidden=salary;document.getElementById('income-source').hidden=salary||!isIncome;document.getElementById('date-label').hidden=type.value==='month';document.getElementById('date').required=type.value!=='month';document.getElementById('source-month-label').hidden=type.value!=='month';document.getElementById('month-label').hidden=type.value!=='month';document.getElementById('source-month').required=document.getElementById('destination').required=type.value==='month';document.getElementById('category-label').hidden=type.value!=='expense';document.getElementById('category').required=type.value==='expense';document.getElementById('edit-location-label').hidden=!editingId;document.getElementById('delete-movement').hidden=!editingId;document.getElementById('save-movement').textContent=live?(editingId?'Guardar cambios':'Guardar movimiento'):(editingId?'Guardar cambios en el ejemplo':'Agregar solo al ejemplo');location=document.getElementById('edit-location').value;document.getElementById('modal-note').textContent=salary?'Se registra en Efectivo como ingreso propio. La fecha empieza en hoy; podés cambiarla para cargar días anteriores.':type.value==='transfer'?`Destino: ${location==='cash'?'Virtual':'Efectivo'}. Editar o eliminar afecta ambas partes.`:type.value==='month'?'Elegí la fecha de salida y la fecha de entrada, en meses diferentes. Editar o eliminar afecta ambas partes.':'';}
form.addEventListener('change',fields);document.getElementById('close-modal').addEventListener('click',()=>dialog.close());
document.getElementById('delete-movement').addEventListener('click',async()=>{const op=operations.find(op=>op.id===editingId);if(!op||writeBusy)return;const linked=['transfer','month'].includes(op.kind);if(!confirm(`¿Eliminar “${op.description}”? ${linked?'Se eliminarán las dos partes vinculadas. ':''}Se recalcularán los saldos y totales.`))return;if(await change(data=>{const index=data.operations.findIndex(item=>item.id===op.id);if(index<0)throw new Error('El movimiento ya fue eliminado.');data.operations.splice(index,1);},'Movimiento eliminado.',formRevision))dialog.close();});
document.addEventListener('submit',async event=>{if(event.target.id!=='category-form')return;event.preventDefault();const name=document.getElementById('category-name').value.trim();if(!name||categories.some(c=>c.name.toLocaleLowerCase()===name.toLocaleLowerCase())){document.getElementById('category-error').textContent='Ingresá un nombre nuevo para la categoría.';return;}if(await change(data=>data.categories.push({id:crypto.randomUUID(),name}),'Categoría agregada.'))document.getElementById('category-name').value='';});
form.addEventListener('submit',async event=>{event.preventDefault();if(writeBusy)return;const raw=document.getElementById('amount').value.trim();if(!/^\d+(?:[,.]\d{1,2})?$/.test(raw)){document.getElementById('form-error').textContent='Ingresá un importe como 1500 o 1500,50, sin separador de miles.';return;}const [whole,fraction='']=raw.replace(',','.').split('.');const cents=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(cents)||cents<=0){document.getElementById('form-error').textContent='Ingresá un importe válido mayor que cero.';return;}const kind=type.value,date=document.getElementById('date').value;const incomeChoice=salary?'salary':form.elements.incomeSource.value;
const incomeSource=incomeChoice==='contribution'?'contribution':'own';
const incomeCategory=kind==='income'&&incomeSource==='own'?incomeChoice:undefined;
const defaultIncome={salary:'Sueldo diario',mel:'Sueldo Mel',misa:'Sueldo Misa',extra:'Otro ingreso propio',contribution:'Ingreso ajeno para pagos'}[incomeChoice];
const description=salary?'Sueldo diario':document.getElementById('description').value.trim()||(kind==='income'?defaultIncome:({expense:'Gasto de ejemplo',transfer:'Transferencia entre ubicaciones',month:'Pase entre meses','saving-out':'Enviado a Ahorro / Préstamos','saving-in':'Devuelto desde Ahorro / Préstamos'}[kind]).replace(live?' de ejemplo':'__never__',''));let legs;
if(kind==='transfer')legs=[{location,date,cents:-cents},{location:location==='cash'?'virtual':'cash',date,cents}];else if(kind==='month'){const sourceDate=document.getElementById('source-month').value,targetDate=document.getElementById('destination').value;if(!sourceDate||!targetDate||sourceDate.slice(0,7)===targetDate.slice(0,7)){document.getElementById('form-error').textContent='Elegí una fecha de salida y una de entrada en meses diferentes.';return;}legs=[{location,date:sourceDate,cents:-cents,description:'Para '+dateName(targetDate)+' · '+description},{location,date:targetDate,cents,description:'Desde '+dateName(sourceDate)+' · '+description}];}else legs=[{location,date,cents:['expense','saving-out'].includes(kind)?-cents:cents}];const op={id:editingId||draftId,kind,incomeSource:kind==='income'?incomeSource:undefined,incomeCategory,categoryId:kind==='expense'?document.getElementById('category').value:undefined,description,legs};if(await change(data=>{const clean=JSON.parse(JSON.stringify(op));if(editingId){const index=data.operations.findIndex(old=>old.id===editingId);if(index<0)throw new Error('El movimiento ya fue eliminado.');data.operations.splice(index,1,clean);}else data.operations.push(clean);},editingId?'Cambios guardados.':'Movimiento guardado.',formRevision))dialog.close();});

const iconPaths={categories:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',home:'M3 10 12 3l9 7M5 9v12h14V9M9 21v-7h6v7',cash:'M3 6h18v13H3zM3 10h18M15 14h3',virtual:'M7 3h10v18H7zM10 17h4',evolution:'M4 20V4M4 20h17M7 15l4-4 4 2 5-7',backup:'M8 19H6a4 4 0 0 1-1-8 7 7 0 0 1 13-3 5 5 0 0 1 1 10h-3M12 12v9M9 18l3 3 3-3',movements:'M5 6h14M5 12h14M5 18h14'};
document.querySelectorAll('nav button').forEach(button=>{const text=button.textContent;button.innerHTML=`<svg class="nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${iconPaths[button.dataset.tab]}"></path></svg><span>${text}</span>`;});

render();

function applyState(state){const openDetails=[...screen.querySelectorAll('details[open]')].map(el=>({category:el.dataset.categoryId,month:el.dataset.evolutionMonth}));const categoryDraft=document.getElementById('category-name')?.value;liveRevision=state.revision;operations.splice(0,operations.length,...state.ledger.operations);categories.splice(0,categories.length,...state.ledger.categories);render();if(categoryDraft&&document.getElementById('category-name'))document.getElementById('category-name').value=categoryDraft;for(const item of openDetails){const el=item.category?screen.querySelector('[data-category-id="'+item.category+'"]'):item.month?screen.querySelector('[data-evolution-month="'+item.month+'"]'):null;if(el)el.open=true;}}
function syncWriteButtons(){for(const element of document.querySelectorAll('[data-move],[data-edit],[data-rename-category],[data-remove-category],#category-form button,#save-movement,#delete-movement'))element.disabled=writeBusy||(live&&!liveReady);if(live)document.getElementById('app-logout').disabled=writeBusy;}
function writeStatus(message){if(live)document.getElementById('app-status').textContent=message;}
async function change(mutator,message,expectedRevision=liveRevision){if(writeBusy||(live&&!liveReady)){toast('Primero confirmá el acceso y esperá el guardado.');return false;}writeBusy=true;syncWriteButtons();const data=JSON.parse(JSON.stringify({operations,categories}));try{mutator(data);if(live){validateLedger(data);writeStatus('Guardando en Firebase…');const result=await liveStore.save(data,expectedRevision,crypto.randomUUID());pendingState=null;applyState(result);writeStatus('Guardado confirmado en Firebase.');window.DriveBackup.changed();}else{operations.splice(0,operations.length,...data.operations);categories.splice(0,categories.length,...data.categories);render();}toast(live?message:message+' Solo en la demostración.');return true;}catch(error){const detail=live?liveError(error):error.message;writeStatus(detail);document.getElementById('form-error').textContent=detail;toast(detail);if(live&&error.code==='ledger/conflict'){try{applyState(await liveStore.read());}catch{}document.getElementById('form-error').textContent=detail+' Cerrá el formulario y abrilo nuevamente.';}return false;}finally{writeBusy=false;if(pendingState){const state=pendingState;pendingState=null;applyState(state);}syncWriteButtons();}}
let liveError=error=>error.message;
async function liveSnapshot(){if(!liveReady)throw new Error('Primero confirmá el acceso con Firebase.');return makeBackup(await liveStore.read());}
async function exportLedger(){try{const backup=await liveSnapshot();const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='control-gastos_'+new Date().toISOString().replaceAll(':','-')+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Descarga solicitada. Comprobá el archivo en Descargas.');}catch(error){toast(liveError(error));}}
async function restoreLedger(backup){if(!liveReady||writeBusy)return;let target;try{target=await validateBackup(backup);}catch(error){toast(error.message);return;}if(writeBusy)return;writeBusy=true;syncWriteButtons();try{const before=await liveStore.read();if(!confirm(`¿Restaurar la copia del ${new Date(backup.createdAt).toLocaleString('es-AR')} (revisión ${backup.revision}) con ${target.operations.length} movimientos sobre la revisión actual ${before.revision}? Reemplazará todos los movimientos y categorías actuales. Primero se conservará una copia completa del estado actual en Drive.`))return;writeStatus('Conservando copia previa en Drive…');const safety=await window.DriveBackup.request('/backups',await makeBackup(before));if(safety.saved!==true||!safety.file?.id||!safety.file?.createdTime)throw new Error('No se confirmó la copia previa. No se restauró.');const result=await liveStore.save(target,before.revision,crypto.randomUUID());pendingState=null;applyState(result);writeStatus('Restauración confirmada en Firebase. Copia previa conservada en Drive.');window.DriveBackup.changed();toast('Restauración confirmada. La nueva copia de Drive se informa por separado.');}catch(error){writeStatus(liveError(error));toast(liveError(error));}finally{writeBusy=false;if(pendingState){applyState(pendingState);pendingState=null;}syncWriteButtons();}}
if(live){
 window.DriveBackup.init({app:'gastos',getBackup:liveSnapshot,restoreEvent:'gastos:restore-ledger',restoreLabel:'Restaurar movimientos',returnTo:'app.html'});
 window.addEventListener('gastos:restore-ledger',event=>restoreLedger(event.detail));
 document.addEventListener('change',async event=>{if(event.target.id!=='import-ledger')return;const file=event.target.files?.[0];if(!file)return;try{if(file.size>2_000_000)throw new Error('El archivo es demasiado grande.');await restoreLedger(JSON.parse(await file.text()));}catch(error){toast(liveError(error));}finally{event.target.value='';}});
 try{const module=await import('./live-store.js?v=monthly-summary-1');liveError=module.errorMessage;liveStore=await module.connectStore({onState:state=>{if(state.revision<liveRevision)return;if(writeBusy)pendingState=state;else{liveReady=true;liveLoaded=true;applyState(state);if(state.revision>0)window.DriveBackup.changed();}},onSignedOut:()=>{liveReady=false;liveLoaded=false;liveRevision=0;pendingState=null;operations.splice(0);categories.splice(0,categories.length,...emptyLedger().categories);if(dialog.open)dialog.close();render();},onStatus:(message,ready,rules)=>{liveReady=ready&&navigator.onLine;document.getElementById('app-status').textContent=message;document.getElementById('rules-help').hidden=!rules;syncWriteButtons();}});}catch(error){writeStatus(liveError(error));}
 document.getElementById('copy-rules').addEventListener('click',async()=>{try{const text=await(await fetch('firestore.rules',{cache:'no-store'})).text();await navigator.clipboard.writeText(text);toast('Reglas copiadas. Pegalas completas en Firestore → Reglas y publicá.');}catch{toast('No se pudo copiar. Abrí el enlace de las reglas para copiarlas.');}});
}
