const screen = document.getElementById('screen');
const parts = new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
const part = name => parts.find(p=>p.type===name).value;
const today = `${part('year')}-${part('month')}-${part('day')}`, currentMonth=today.slice(0,7);
const prevDate = new Date(`${currentMonth}-15T12:00:00Z`); prevDate.setUTCMonth(prevDate.getUTCMonth()-1);
const previousMonth = prevDate.toISOString().slice(0,7);
const exampleDay = Number(part('day'))>1 ? `${currentMonth}-${String(Number(part('day'))-1).padStart(2,'0')}` : today;
const money = cents => new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',minimumFractionDigits:2,maximumFractionDigits:2}).format(cents/100);
const monthName = value => new Intl.DateTimeFormat('es-AR',{month:'long',year:'numeric',timeZone:'America/Argentina/Buenos_Aires'}).format(new Date(value+'-15T12:00:00Z'));
const escape = text => String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let tab='home', month=currentMonth, location='cash', salary=false, historical=false;
const operations = [
 {kind:'income',owner:'own',description:'Sueldo diario',legs:[{location:'cash',date:exampleDay,cents:1500000}]},
 {kind:'transfer',description:'De Efectivo a Virtual',legs:[{location:'cash',date:exampleDay,cents:-700000},{location:'virtual',date:exampleDay,cents:700000}]},
 {kind:'expense',owner:'own',description:'Viaje al trabajo',legs:[{location:'cash',date:today,cents:-85000}]},
 {kind:'expense',owner:'own',description:'Compra del día',legs:[{location:'virtual',date:today,cents:-100000}]},
 {kind:'saving-out',description:'Enviado a Ahorro / Préstamos',legs:[{location:'virtual',date:today,cents:-150000}]},
 {kind:'income',owner:'other',description:'Compra compartida de ejemplo',legs:[{location:'virtual',date:exampleDay,cents:10000000}]},
 {kind:'expense',owner:'other',description:'Pago de compra compartida',legs:[{location:'virtual',date:today,cents:-9000000}]},
 {kind:'income',owner:'own',description:'Ingresos del mes anterior',legs:[{location:'cash',date:previousMonth+'-10',cents:1200000}]},
 {kind:'expense',owner:'own',description:'Gastos del mes anterior',legs:[{location:'cash',date:previousMonth+'-12',cents:-800000}]}
];
const rows = () => operations.flatMap(op=>op.legs.map(leg=>({...leg,op})));
const balance = (loc,m=month) => rows().filter(r=>r.date.slice(0,7)===m&&(!loc||r.location===loc)).reduce((sum,r)=>sum+r.cents,0);
function monthBar(title){return `<h2 class="page-title">${title}</h2><div class="month-navigation"><button class="month-arrow" type="button" data-month-step="-1" aria-label="Mes anterior">‹</button><button class="month-title" type="button" id="choose-month" aria-label="Elegir mes"><strong>${monthName(month)}</strong><small>${month===currentMonth?'Mes actual':'Mes consultado'}</small></button><button class="month-arrow" type="button" data-month-step="1" aria-label="Mes siguiente">›</button></div><div id="month-chooser" class="month-chooser" hidden><label>Ir directamente a un mes<input id="month-picker" type="month" value="${month}" aria-label="Mes consultado"></label></div>`;}
function shiftMonth(step){const date=new Date(month+'-15T12:00:00Z');date.setUTCMonth(date.getUTCMonth()+step);month=date.toISOString().slice(0,7);historical=month!==currentMonth;render();}

function toast(text){const el=document.getElementById('toast');el.textContent=text;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.textContent='',4500);}
function go(next){tab=next;if(!historical&&(next==='cash'||next==='evolution'))month=currentMonth;render();if(next==='cash')requestAnimationFrame(()=>document.getElementById('today')?.scrollIntoView({block:'center',behavior:'smooth'}));else window.scrollTo({top:0});}
function ownTotals(m){let income=0,expense=0,savings=0;for(const r of rows().filter(r=>r.date.slice(0,7)===m)){
 if(r.op.kind==='income'&&r.op.owner==='own')income+=r.cents;
 if(r.op.kind==='expense'&&r.op.owner==='own')expense-=r.cents;
 if(r.op.kind==='saving-out'||r.op.kind==='saving-in')savings-=r.cents;
 }return {income,expense,savings};}
function entry(r){const label=r.op.kind==='transfer'?'Transferencia · no es ingreso ni gasto':r.op.kind==='month'?'Pase vinculado · sin arrastre automático':r.op.kind.startsWith('saving')?'Ahorro / Préstamos':r.op.owner==='other'?'Ajeno · caso abierto':'Mío';return `<div class="entry"><div><strong>${escape(r.description || r.op.description)}</strong><small>${label}</small></div><span class="money ${r.cents>=0?'positive':'negative'}">${r.cents>=0?'+':'−'}${money(Math.abs(r.cents))}</span></div>`;}
function home(){const otherMonths=[...new Set(rows().map(r=>r.date.slice(0,7)))].filter(m=>m!==month);const others=otherMonths.reduce((s,m)=>s+balance(null,m),0);return `${monthBar('Inicio')}<section class="hero"><p>Total disponible · ${monthName(month)}</p><div class="balance">${money(balance())}</div><small>Efectivo + Virtual del mes consultado</small></section><div class="accounts"><button class="account-card" data-go="cash"><span>Efectivo</span><strong>${money(balance('cash'))}</strong><small>Dinero actual →</small></button><button class="account-card" data-go="virtual"><span>Virtual</span><strong>${money(balance('virtual'))}</strong><small>Dinero actual →</small></button></div><div class="actions"><button class="primary" data-move="salary">+ Sueldo diario</button><button class="action" data-move="cash">Movimiento Efectivo</button><button class="action" data-move="virtual">Movimiento Virtual</button></div><p class="muted">En otros meses: ${money(others)}. Cada saldo permanece en su mes hasta que registres un pase.</p>`;}
function account(loc){const title=loc==='cash'?'Efectivo':'Virtual';const relevant=rows().filter(r=>r.location===loc&&r.date.slice(0,7)===month);let days=[...new Set(relevant.map(r=>r.date))];if(month===currentMonth)days.push(today);days=[...new Set(days)].sort();return `${monthBar(title)}<section class="hero"><p>Dinero actual · ${monthName(month)}</p><div class="balance">${money(balance(loc))}</div></section><div class="section-head"><h3>Movimientos del mes</h3><button class="small-button" data-go="others">Resumen de ajenos →</button></div><div class="days">${days.length?days.map(day=>{const records=relevant.filter(r=>r.date===day);return `<section class="day ${day===today?'today':''}" ${day===today?'id="today"':''}><div class="date-col"><b>${Number(day.slice(8))}</b>${day===today?'HOY':new Intl.DateTimeFormat('es-AR',{weekday:'short',timeZone:'America/Argentina/Buenos_Aires'}).format(new Date(day+'T12:00:00Z'))}</div><div>${records.length?records.map(entry).join(''):'<div class="empty">Sin movimientos hoy</div>'}</div></section>`;}).join(''):'<p class="empty">No hay movimientos en este mes de ejemplo.</p>'}</div><div class="section-head"><button class="action" data-move="${loc}">+ Movimiento ${title}</button></div>`;}
function evolution(){const months=[...new Set([currentMonth,...rows().map(r=>r.date.slice(0,7))])].sort().reverse();return `<div class="section-head"><h2>Evolución</h2><span class="pill">Solo mi dinero</span></div><p class="muted">Efectivo + Virtual. Sin ajenos, transferencias ni pases.</p><div class="evolution-labels"><span>Mes</span><span>Ingresos propios</span><span>Gastos propios</span><span>Neto a Ahorro / Préstamos</span></div><div class="evolution">${months.map(m=>{const t=ownTotals(m);return `<details ${m===currentMonth?'id="current-evolution"':''}><summary class="evolution-row"><b>${new Intl.DateTimeFormat('es-AR',{month:'short',timeZone:'America/Argentina/Buenos_Aires'}).format(new Date(m+'-15T12:00:00Z'))}<small class="muted"> ${m.slice(0,4)}</small></b><span class="positive">${money(t.income)}</span><span>${money(t.expense)}</span><span>${money(t.savings)}</span></summary><div class="detail-body"><p class="muted">${monthName(m)}</p>${rows().filter(r=>r.date.slice(0,7)===m&&((r.op.owner==='own'&&['income','expense'].includes(r.op.kind))||r.op.kind.startsWith('saving'))).map(r=>`<div class="detail-line"><span>${escape(r.description || r.op.description)}</span><span>${money(Math.abs(r.cents))}</span></div>`).join('')}</div></details>`;}).join('')}</div>`;}
function others(){const received=rows().filter(r=>r.op.owner==='other'&&r.cents>0).reduce((s,r)=>s+r.cents,0),paid=-rows().filter(r=>r.op.owner==='other'&&r.cents<0).reduce((s,r)=>s+r.cents,0);return `<button class="back-button" data-go="virtual">← Volver a Virtual</button><h2>Resumen de ajenos</h2><p class="muted">Todos los meses y ambas ubicaciones, sin duplicar dinero.</p><section class="info-card"><h3>Compra compartida de ejemplo <span class="pill">Abierto</span></h3><div class="metrics"><div><span>Total recibido</span><strong>${money(received)}</strong></div><div><span>Total pagado</span><strong>${money(paid)}</strong></div><div><span>Diferencia sin resolver</span><strong>${money(received-paid)}</strong></div><div><span>Propio confirmado</span><strong>${money(0)}</strong></div></div><p>La diferencia no es una ganancia propia ni una obligación de pago confirmada. Este caso aún está por resolver.</p></section><section class="info-card"><h3>1 caso pendiente de resolver</h3><p>Al cerrar un caso se confirma la diferencia acordada. Su reconocimiento como ingreso propio no vuelve a sumar dinero al saldo.</p></section>`;}
function backup(){return `<h2>Respaldo</h2><p class="muted">Diseño de ejemplo · estos estados son ilustrativos.</p><section class="info-card"><span class="pill">Firebase</span><h3 style="margin-top:10px">Datos guardados</h3><p>Así se mostrará la confirmación del guardado principal.</p></section><section class="info-card"><span class="pill">Google Drive</span><h3 style="margin-top:10px">Copia guardada</h3><p>Última copia exitosa: fecha y hora argentina. Requiere la app abierta e Internet.</p><button class="action" data-toast="Esta es una vista de diseño. La prueba real está en el enlace inferior.">Crear copia manual</button></section><section class="info-card"><h3>Copias anteriores</h3><p>Listado, descarga y restauración con confirmación. Las copias anteriores se conservan.</p><button class="action" data-toast="El listado real está en la página de prueba de respaldos.">Consultar copias</button></section><p><a href="drive-respaldos.html">Abrir la prueba real de respaldos →</a></p>`;}
function history(){const months=[...new Set([currentMonth,...rows().map(r=>r.date.slice(0,7))])].sort().reverse();return `${monthBar('Historial')}<p class="muted">Abrí un mes y recorré Inicio, Efectivo, Virtual y Movimientos con los datos de ese período.</p><button class="primary" id="open-history">Abrir mes elegido</button><div class="section-head"><h3>Meses con movimientos</h3></div><div class="history-list">${months.map(m=>`<button class="account-card history-card" data-history-month="${m}"><span>${monthName(m)}</span><strong>${money(balance(null,m))}</strong><small>Disponible en ese mes →</small></button>`).join('')}</div><p class="muted">Los meses se conservan por separado. Abrir un mes no traslada su saldo.</p>`;}
function movements(){const items=operations.map(op=>{const visible=op.legs.filter(leg=>leg.date.slice(0,7)===month);if(!visible.length)return null;const first=visible[0],linked=op.kind==='transfer'||op.kind==='month';const places=[...new Set(op.legs.map(leg=>leg.location==='cash'?'Efectivo':'Virtual'))].join(' → ');const title=op.kind==='month'?`${monthName(op.legs[0].date.slice(0,7))} → ${monthName(op.legs[1].date.slice(0,7))}`:op.description;return {date:first.date,html:`<div class="entry"><div><strong>${escape(title)}</strong><small>${places} · ${linked?'Una operación vinculada':op.kind.startsWith('saving')?'Ahorro / Préstamos':op.owner==='other'?'Ajeno':'Mío'}</small></div><span class="money ${linked?'':first.cents>=0?'positive':'negative'}">${linked?'':first.cents>=0?'+':'−'}${money(Math.abs(first.cents))}</span></div>`};}).filter(Boolean).sort((a,b)=>b.date.localeCompare(a.date));const days=[...new Set(items.map(item=>item.date))];return `${monthBar('Movimientos')}<p class="muted">Todo Efectivo y Virtual del mes, incluidos ajenos, transferencias, pases y Ahorro / Préstamos.</p><div class="days">${days.length?days.map(day=>`<section class="day"><div class="date-col"><b>${Number(day.slice(8))}</b>${new Intl.DateTimeFormat('es-AR',{weekday:'short',timeZone:'America/Argentina/Buenos_Aires'}).format(new Date(day+'T12:00:00Z'))}</div><div>${items.filter(item=>item.date===day).map(item=>item.html).join('')}</div></section>`).join(''):'<div class="empty">No hay movimientos en este mes de ejemplo.</div>'}</div>`;}
function selectHistory(value){if(!/^\d{4}-\d{2}$/.test(value))return;month=value;historical=month!==currentMonth;go('home');}
function render(){screen.innerHTML=(historical?`<div class="history-banner"><span>Historial · ${monthName(month)}</span><button id="return-current" type="button">Volver al mes actual</button></div>`:'')+(tab==='history'?history():tab==='movements'?movements():tab==='home'?home():tab==='cash'?account('cash'):tab==='virtual'?account('virtual'):tab==='evolution'?evolution():tab==='others'?others():backup());document.querySelectorAll('nav button').forEach(b=>{if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});document.getElementById('month-picker')?.addEventListener('change',e=>{if(e.target.value){month=e.target.value;historical=month!==currentMonth;render();}});}
document.addEventListener('click',event=>{const step=event.target.closest('[data-month-step]');if(step){shiftMonth(Number(step.dataset.monthStep));return;}if(event.target.closest('#choose-month')){const chooser=document.getElementById('month-chooser');chooser.hidden=!chooser.hidden;if(!chooser.hidden)document.getElementById('month-picker').focus();return;}if(event.target.closest('#return-current')){month=currentMonth;historical=false;go(tab);return;}if(event.target.closest('#open-history')){selectHistory(month);return;}const historyButton=event.target.closest('[data-history-month]');if(historyButton){selectHistory(historyButton.dataset.historyMonth);return;}const goButton=event.target.closest('[data-go]');if(goButton)go(goButton.dataset.go);const nav=event.target.closest('[data-tab]');if(nav)go(nav.dataset.tab);const move=event.target.closest('[data-move]');if(move)openMovement(move.dataset.move);const notice=event.target.closest('[data-toast]');if(notice)toast(notice.dataset.toast);});
const dialog=document.getElementById('movement'),form=document.getElementById('movement-form'),type=document.getElementById('type');
function openMovement(which){form.reset();salary=which==='salary';location=salary?'cash':which;document.getElementById('dialog-title').textContent=salary?'+ Sueldo diario':`Movimiento ${location==='cash'?'Efectivo':'Virtual'}`;document.getElementById('date').value=today;document.getElementById('source-month').value=month;const next=new Date(currentMonth+'-15T12:00:00Z');next.setUTCMonth(next.getUTCMonth()+1);document.getElementById('destination').value=month===currentMonth?next.toISOString().slice(0,7):currentMonth;type.value=salary?'income':'expense';document.getElementById('form-error').textContent='';fields();dialog.showModal();document.getElementById('amount').focus();}
function fields(){const common=['income','expense'].includes(type.value);for(const id of ['type-label','description-label','date-label'])document.getElementById(id).hidden=salary;document.getElementById('ownership').hidden=salary||!common;document.getElementById('date-label').hidden=salary||type.value==='month';document.getElementById('source-month-label').hidden=type.value!=='month';document.getElementById('month-label').hidden=type.value!=='month';document.getElementById('case-label').hidden=salary||!common||form.elements.owner.value!=='other';document.getElementById('modal-note').textContent=salary?'Hoy, en Efectivo y como ingreso propio. Fecha e importe se podrán corregir desde el historial en la app final.':type.value==='transfer'?`Destino: ${location==='cash'?'Virtual':'Efectivo'}. Una sola operación para ambas ubicaciones.`:type.value==='month'?`Sale de ${location==='cash'?'Efectivo':'Virtual'} en el mes de origen y entra en la misma ubicación en el mes de destino. Se registra una sola vez.`:'';}
form.addEventListener('change',fields);document.getElementById('close-modal').addEventListener('click',()=>dialog.close());
form.addEventListener('submit',event=>{event.preventDefault();const raw=document.getElementById('amount').value.trim();if(!/^\d+(?:[,.]\d{1,2})?$/.test(raw)){document.getElementById('form-error').textContent='Ingresá un importe como 1500 o 1500,50, sin separador de miles.';return;}const [whole,fraction='']=raw.replace(',','.').split('.');const cents=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(cents)||cents<=0){document.getElementById('form-error').textContent='Ingresá un importe válido mayor que cero.';return;}const kind=type.value,date=salary?today:document.getElementById('date').value;const description=salary?'Sueldo diario':document.getElementById('description').value.trim()||({expense:'Gasto de ejemplo',income:'Ingreso de ejemplo',transfer:'Transferencia entre ubicaciones',month:'Pase entre meses','saving-out':'Enviado a Ahorro / Préstamos','saving-in':'Devuelto desde Ahorro / Préstamos'}[kind]);const owner=salary?'own':form.elements.owner.value;let legs;
if(kind==='transfer')legs=[{location,date,cents:-cents},{location:location==='cash'?'virtual':'cash',date,cents}];else if(kind==='month'){const origin=document.getElementById('source-month').value,dest=document.getElementById('destination').value;if(!origin||!dest||origin===dest){document.getElementById('form-error').textContent='Elegí un mes de origen y uno de destino diferentes.';return;}const last=new Date(Number(origin.slice(0,4)),Number(origin.slice(5,7)),0).getDate();const sourceDate=origin===currentMonth?today:origin+'-'+String(last).padStart(2,'0');const targetDate=dest===currentMonth?today:dest+'-01';legs=[{location,date:sourceDate,cents:-cents,description:'Para '+monthName(dest)+(document.getElementById('description').value.trim()?' · '+description:'')},{location,date:targetDate,cents,description:'Desde '+monthName(origin)+(document.getElementById('description').value.trim()?' · '+description:'')}];}else legs=[{location,date,cents:['expense','saving-out'].includes(kind)?-cents:cents}];operations.push({kind,owner,description,legs});dialog.close();render();toast('Agregado solo a la demostración. No se guardó en Firebase.');});
render();
