import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import {getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged,signOut,setPersistence,browserLocalPersistence} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import * as sdk from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
import {createLedgerRepository} from './ledger-repository.js';
const app=initializeApp({apiKey:'AIzaSyBB4GrQQeRwgQlJ_jFqMbJzRU4FOTaI1cw',authDomain:'control-de-gastos-72453.firebaseapp.com',projectId:'control-de-gastos-72453',appId:'1:585615744945:web:e720a412a6bbd7c6382790'});
export function errorMessage(error){return ({'permission-denied':'Falta habilitar el guardado privado. Publicá las reglas de Firestore indicadas abajo con la cuenta autorizada.','unavailable':'No hay conexión con Firebase. No se confirmó el guardado. Conservá el formulario e intentá cuando vuelva Internet.','resource-exhausted':'Firebase alcanzó su cuota. No se confirmó el guardado; intentá más tarde.','auth/popup-blocked':'Permití la ventana de Google e intentá de nuevo.','auth/popup-closed-by-user':'No se completó el acceso con Google.','auth/network-request-failed':'No se pudo conectar con Google. Revisá Internet.'})[error.code]||error.message||'No se pudo completar la operación.';}
export async function connectStore({onState,onStatus,onSignedOut}){
 const auth=getAuth(app),db=sdk.getFirestore(app);let repository=null,unsubscribe=null,generation=0;
 const login=document.getElementById('app-login'),logout=document.getElementById('app-logout'),retry=document.getElementById('app-retry');
 function failure(error){onStatus(errorMessage(error),false,error.code==='permission-denied');}
 async function subscribe(user){const ownGeneration=++generation;unsubscribe?.();unsubscribe=null;repository=null;onSignedOut();login.hidden=!!user;logout.hidden=!user;retry.hidden=!user;if(!user){onStatus('Entrá con Google para abrir tus movimientos.',false);return;}onStatus('Comprobando tus datos en Firebase…',false);const candidate=createLedgerRepository(db,user.uid,sdk);try{const state=await candidate.read();if(ownGeneration!==generation)return;repository=candidate;onState(state);onStatus(state.revision?'Datos confirmados en Firebase.':'Cuenta conectada. Todavía no registraste movimientos.',true);unsubscribe=candidate.watch(state=>{if(ownGeneration===generation){onState(state);onStatus(state.revision?'Datos confirmados en Firebase.':'Cuenta conectada. Todavía no registraste movimientos.',true);}},error=>{if(ownGeneration===generation){repository=null;onSignedOut();failure(error);}});}catch(error){if(ownGeneration===generation)failure(error);}}
 await setPersistence(auth,browserLocalPersistence);login.disabled=false;
 onAuthStateChanged(auth,subscribe,failure);
 login.addEventListener('click',async()=>{login.disabled=true;try{const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});await signInWithPopup(auth,provider);}catch(error){failure(error);}finally{login.disabled=false;}});
 logout.addEventListener('click',()=>signOut(auth).catch(failure));retry.addEventListener('click',()=>subscribe(auth.currentUser));
 window.addEventListener('online',()=>subscribe(auth.currentUser));window.addEventListener('offline',()=>onStatus('Sin Internet. Los datos mostrados son la última lectura; no se pueden guardar cambios.',false));
 return {async read(){if(!repository||!auth.currentUser)throw new Error('Primero conectá tu cuenta y confirmá el acceso.');const repo=repository,ownGeneration=generation;const result=await repo.read();if(ownGeneration!==generation)throw new Error('La sesión cambió. Volvé a entrar.');return result;},async save(ledger,revision,id){if(!repository||!auth.currentUser||!navigator.onLine)throw new Error('Necesitás la cuenta conectada e Internet para guardar.');const repo=repository,ownGeneration=generation;const result=await repo.save(ledger,revision,id);if(ownGeneration!==generation)throw new Error('La sesión cambió durante el guardado. Revisá los datos al volver a entrar.');return result;}};
}
